### ISSUE TITLE
Ability to set MSBuild version.

### ISSUE THREAD

**Issue by Psychobilly87** [vigoo/bari#141]
Maybe with exe path. 
e.g. `"C:\Program Files (x86)\MSBuild\12.0\Bin\amd64\MSBuild.exe"`

**Comment by vigoo** [comment]
There will be a suite-level parameter block called `msbuild` with a property where msbuild's version can be set using predefined (enum) values and `default` which means use the `msbuild.exe` on the path.

**Comment by vigoo** [comment]
https://github.com/vigoo/bari/wiki/MSBuildProperties
