### ISSUE TITLE
Support VS2013 SLN version

### ISSUE THREAD

**Issue by vigoo** [vigoo/bari#142]
When
```yaml
msbuild:
    version: VS2013
```
then instead of
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 2012
```

put
```
Microsoft Visual Studio Solution File, Format Version 13.00
# Visual Studio 2013
```

to the header of `.sln` files.

**Comment by vigoo** [comment]
@attixray

**Comment by attixray** [comment]
I have double checked this:
The first line is the same with both VS2012, 2013:
Microsoft Visual Studio Solution File, Format Version 12.00
(But it is ignored anyway..)

The "Open file with" decision is based on the 2nd line:
# Visual Studio 2012 or 2013
