### ISSUE TITLE
Gallio's download link is not working

### ISSUE THREAD

**Issue by Psychobilly87** [vigoo/bari#158]
This link:
http://mb-unit.googlecode.com/files/GallioBundle-3.4.14.0.zip

**Comment by vigoo** [comment]
It could download it from [NuGet](https://www.nuget.org/packages/GallioBundle/)

**Comment by Psychobilly87** [comment]
Yes, we could get it also, but Bari can't right now.

**Comment by vigoo** [comment]
.... this was a comment on how I should rewrite the downloader ... :)
